# first, ansible-galaxy install openmicroscopy.omero-server
- hosts: localhost
  roles:
    - role: openmicroscopy.omero-server
      postgresql_users_databases:
      - user: omero
        password: omero
        databases: [omero]
      omero_systemd_setup: True

  vars:
    omero_upgrade: True
    omero_prestart_file: "files/OMERO-52-omero.j2"
