---

- src: openmicroscopy.postgresql
  version: 2.0.0

- name: openmicroscopy.omero-common
  src:  https://github.com/openmicroscopy/ansible-role-omero-common.git
  # TODO: workaround for https://github.com/ansible/galaxy-issues/issues/259

- name: openmicroscopy.omego

- name: openmicroscopy.omero-server

- name: openmicroscopy.omero-web

- name: omero-user
  src:  https://github.com/openmicroscopy/ansible-role-omero-user.git
  # TODO: workaround for missing owner
